### v1 models
# Models: https://huggingface.co/collections/p1atdev/dart-danbooru-tags-transformer-65d687604ff57dc62ae40945
- name: v1 sft (eager)
  version: v1
  model_name_or_path: p1atdev/dart-v1-sft
  model_type: eager
  prompt_template_id: V1_SFT # this refers to the prompt template in prompt_templates.yml

- name: v1 sft (onnx)
  version: v1
  model_name_or_path: p1atdev/dart-v1-sft
  model_type: onnx
  onnx_file_name: model.onnx
  prompt_template_id: V1_SFT

- name: v1 sft (onnx quant)
  version: v1
  model_name_or_path: p1atdev/dart-v1-sft
  model_type: onnx
  onnx_file_name: model_quantized.onnx
  prompt_template_id: V1_SFT
###

### v2 models
# Models: https://huggingface.co/collections/p1atdev/dart-v2-danbooru-tags-transformer-v2-66291115701b6fe773399b0a
- name: v2 sft (eager)
  version: v2
  model_name_or_path: p1atdev/dart-v2-sft
  model_type: eager
  prompt_template_id: V2_SFT

- name: v2 sft (onnx quantized)
  version: v2
  model_name_or_path: p1atdev/dart-v2-sft
  model_type: onnx
  onnx_file_name: model_quantized.onnx
  prompt_template_id: V2_SFT

- name: v2 MoE sft (eager)
  version: v2
  model_name_or_path: p1atdev/dart-v2-moe-sft
  model_type: eager
  prompt_template_id: V2_SFT
###

### v3 models
# Models: https://huggingface.co/collections/p1atdev/dart-v3-preview-6720e2678d16a5fb65a3826d

# - name: v3 sft preview A
#   version: v3
#   model_name_or_path: p1atdev/dart-v3-sft-preview-A
#   model_type: eager
#   prompt_template_id: V3_SFT

###
