### v1 models
- name: v1 sft (eager)
  version: v1
  model_name_or_path: p1atdev/dart-v1-sft
  model_type: eager
  prompt_template_id: V1_SFT # this refers to the prompt template in prompt_templates.yml

- name: v1 sft (onnx)
  version: v1
  model_name_or_path: p1atdev/dart-v1-sft
  model_type: onnx
  onnx_file_name: model.onnx
  prompt_template_id: V1_SFT

- name: v1 sft (onnx quant)
  version: v1
  model_name_or_path: p1atdev/dart-v1-sft
  model_type: onnx
  onnx_file_name: model_quantized.onnx
  prompt_template_id: V1_SFT
###

### v2 models
- name: v2 sft (eager)
  version: v2
  model_name_or_path: p1atdev/dart-v2-sft
  model_type: eager
  prompt_template_id: V2_SFT

- name: v2 sft (onnx quantized)
  version: v2
  model_name_or_path: p1atdev/dart-v2-sft
  model_type: onnx
  onnx_file_name: model_quantized.onnx
  prompt_template_id: V2_SFT

- name: v2 MoE sft (eager)
  version: v2
  model_name_or_path: p1atdev/dart-v2-moe-sft
  model_type: eager
  prompt_template_id: V2_SFT
###

### v3 models
- name: v3 sft 241018+241020-use-group
  version: v3
  model_name_or_path: p1atdev/dart-v3-sft-test-241018_241020-UG
  model_type: eager
  prompt_template_id: V3_USE

- name: v3 sft 241018+241022
  version: v3
  model_name_or_path: p1atdev/dart-v3-llama-8L-241018_241022-sft
  model_type: eager
  prompt_template_id: V3_SFT

- name: v3 sft 241018+241023
  version: v3
  model_name_or_path: p1atdev/dart-v3-llama-8L-241018_241023-sft
  model_type: eager
  prompt_template_id: V3_SFT

- name: v3 sft 241018+241023 2
  version: v3
  model_name_or_path: p1atdev/dart-v3-llama-8L-241018_241023-sft-2
  model_type: eager
  prompt_template_id: V3_SFT

- name: v3 pretrain 241027
  version: v3
  model_name_or_path: p1atdev/dart-v3-llama-7L2KV-241027-1
  model_type: eager
  prompt_template_id: V3_PRETRAIN

- name: v3 sft 241027+241028
  version: v3
  model_name_or_path: p1atdev/dart-v3-llama-7L2KV-241027_241028-sft-1
  model_type: eager
  prompt_template_id: V3_SFT

- name: v3 pretrain 241029
  version: v3
  model_name_or_path: p1atdev/dart-v3-llama-6L4KV-241029-1
  model_type: eager
  prompt_template_id: V3_PRETRAIN
